#!/usr/bin/env node

const spawn = require('child_process').spawnSync;
const path = require('path');
const fs = require('fs')

const BASE_PATH = path.resolve('./packages/stylemug');

function f(p) {
  return BASE_PATH + '/' + p;
}

function assertFile(name) {
  if (!fs.existsSync(f(name))) {
    throw 'File "' + name + '" does not exist';
  }
}

spawn('yarn', ['build'], {
  stdio: 'inherit',
  cwd: BASE_PATH,
});

assertFile('compiler.js');
assertFile('dist/runtime.js');

console.log('🥳');